---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Rifah"
date: "Add the date here"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
install.packages("Lahman")
library(Lahman)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has \_\_\_ observations and \_\_\_ variables.

```{r}
install.packages("tidyverse")
```

### Exercise 2

...

```{r}
mets <- Teams  |>
  dplyr::filter(teamID == "NYN")
my_mets <- mets |>
  dplyr::filter(yearID %in% c(2004:2012))
my_mets |> 
  dplyr::select(yearID,G,W,L)
```

### Exercise 3

...

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, teamID, G, W, L, RA, RS = R) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben

```

### Exercise 4

...

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = W*100/G)
mets_ben
```

### Exercise 5

...

### Exercise 6

...

### Exercise 7

...

### Exercise 8

...

### Exercise 9

...

### Exercise 10

...
